<?php

namespace Icso\Accounting\Enums;

class SettingEnum
{
    public const RESET_NUMBER_MONTH = 'bulan';
    public const RESET_NUMBER_YEAR = 'tahun';
    public const NO_JURNAL_KAS = 'NO_JURNAL_KAS';
    public const NO_JURNAL_UMUM = 'NO_JURNAL_UMUM';
    public const NO_JURNAL_BANK = 'NO_JURNAL_BANK';
    public const NO_JURNAL_GIRO = 'NO_JURNAL_GIRO';
    public const NO_SALDO_AWAL = 'NO_SALDO_AWAL';
    public const NO_PERMINTAAN_PEMBELIAN = 'NO_PERMINTAAN_PEMBELIAN';
    public const NO_ORDER_PEMBELIAN = 'NO_ORDER_PEMBELIAN';
    public const NO_UANG_MUKA_PEMBELIAN = 'NO_UANG_MUKA_PEMBELIAN';
    public const NO_PENERIMAAN_PEMBELIAN = 'NO_PENERIMAAN_PEMBELIAN';
    public const NO_INVOICE_PEMBELIAN = 'NO_INVOICE_PEMBELIAN';
    public const NO_PELUNASAN_PEMBELIAN = 'NO_PELUNASAN_PEMBELIAN';
    public const NO_RETUR_PEMBELIAN = 'NO_RETUR_PEMBELIAN';

    public const COA_UANG_MUKA_PEMBELIAN = "COA_UANG_MUKA_PEMBELIAN";
    public const COA_UANG_MUKA_PENJUALAN = "COA_UANG_MUKA_PENJUALAN";
    public const COA_PPN_MASUKAN = "COA_PPN_MASUKAN";
    public const COA_PPN_KELUARAN = "COA_PPN_KELUARAN";
    public const COA_KAS_BANK = "COA_KAS_BANK";
    public const COA_SEDIAAN = "COA_SEDIAAN";
    public const COA_SEDIAAN_DALAM_PERJALANAN = "COA_SEDIAAN_DALAM_PERJALANAN";
    public const COA_UTANG_USAHA_BELUM_REALISASI = "COA_UTANG_USAHA_BELUM_REALISASI";
    public const COA_UTANG_USAHA = "COA_UTANG_USAHA";
    public const COA_PIUTANG_USAHA = "COA_PIUTANG_USAHA";
    public const COA_POTONGAN_PEMBELIAN = "COA_POTONGAN_PEMBELIAN";
    public const COA_POTONGAN_PENJUALAN = "COA_POTONGAN_PENJUALAN";
    public const COA_BEBAN_POKOK_PENJUALAN = "COA_BEBAN_POKOK_PENJUALAN";
    public const COA_PENJUALAN = "COA_PENJUALAN";
    public const COA_RETUR_PENJUALAN = "COA_RETUR_PENJUALAN";

    public const NO_ORDER_PEMBELIAN_ASET_TETAP = 'NO_ORDER_PEMBELIAN_ASET_TETAP';
    public const NO_UANG_MUKA_PEMBELIAN_ASET_TETAP = 'NO_UANG_MUKA_PEMBELIAN_ASET_TETAP';
    public const NO_PENERIMAAN_PEMBELIAN_ASET_TETAP = 'NO_PENERIMAAN_PEMBELIAN_ASET_TETAP';
    public const NO_INVOICE_PEMBELIAN_ASET_TETAP = 'NO_INVOICE_PEMBELIAN_ASET_TETAP';
    public const NO_PELUNASAN_PEMBELIAN_ASET_TETAP = 'NO_PELUNASAN_PEMBELIAN_ASET_TETAP';

    public const COA_UANG_MUKA_PEMBELIAN_ASET_TETAP = "COA_UANG_MUKA_PEMBELIAN_ASET_TETAP";
    public const COA_BEBAN_DIBAYAR_DIMUKA = "COA_BEBAN_DIBAYAR_DIMUKA";
    public const COA_UTANG_LAIN_LAIN = "COA_UTANG_LAIN_LAIN";
    public const COA_PIUTANG_LAIN_LAIN = "COA_PIUTANG_LAIN_LAIN";

    public const COMPANY_NAME = "COMPANY_NAME";
    public const COMPANY_ADDRESS = "COMPANY_ADDRESS";
    public const COMPANY_PHONE = "COMPANY_PHONE";
    public const COMPANY_FAX = "COMPANY_FAX";
    public const COMPANY_EMAIL = "COMPANY_EMAIL";
    public const COMPANY_WEBSITE = "COMPANY_WEBSITE";
    public const COMPANY_POSTAL_CODE = "COMPANY_POSTAL_CODE";
    public const COMPANY_CITY = "COMPANY_CITY";
    public const COMPANY_PROVINCE = "COMPANY_PROVINCE";
    public const TAX_TYPE_PURCHASE = "TAX_TYPE_PURCHASE";
    public const TAX_TYPE_SALES = "TAX_TYPE_SALES";

}
