<?php

namespace Icso\Accounting\Utils;

class KeyNomor
{
    const KEY_JURNAL_UMUM = 'NO_JURNAL_UMUM';
    const KEY_JURNAL_KAS = 'NO_JURNAL_KAS';
    const KEY_JURNAL_BANK = 'NO_JURNAL_BANK';
    const KEY_JURNAL_GIRO = 'NO_JURNAL_GIRO';
    const KEY_SALDO_AWAL = 'NO_SALDO_AWAL';

    public const NO_PERMINTAAN_PEMBELIAN = 'NO_PERMINTAAN_PEMBELIAN';
    public const NO_ORDER_PEMBELIAN = 'NO_ORDER_PEMBELIAN';
    public const NO_UANG_MUKA_PEMBELIAN = 'NO_UANG_MUKA_PEMBELIAN';
    public const NO_PENERIMAAN_PEMBELIAN = 'NO_PENERIMAAN_PEMBELIAN';
    public const NO_INVOICE_PEMBELIAN = 'NO_INVOICE_PEMBELIAN';
    public const NO_PELUNASAN_PEMBELIAN = 'NO_PELUNASAN_PEMBELIAN';
    public const NO_RETUR_PEMBELIAN = 'NO_RETUR_PEMBELIAN';
    public const NO_BAST = 'NO_BAST';

    public const NO_ORDER_PENJUALAN = 'NO_ORDER_PENJUALAN';
    public const NO_UANG_MUKA_PENJUALAN = 'NO_UANG_MUKA_PENJUALAN';
    public const NO_DELIVERY_ORDER = 'NO_DELIVERY_ORDER';
    public const NO_INVOICE_PENJUALAN = 'NO_INVOICE_PENJUALAN';
    public const NO_PELUNASAN_PENJUALAN = 'NO_PELUNASAN_PENJUALAN';
    public const NO_RETUR_PENJUALAN = 'NO_RETUR_PENJUALAN';
    public const NO_SPK = 'NO_SPK';
    public const NO_ADJUSTMENT_STOCK = 'NO_PENYESUAIAN';
    public const NO_PEMAKAIAN_STOCK = 'NO_PEMAKAIAN';
    public const NO_MUTATION = 'NO_MUTATION';
    public const NO_MUTATION_OUT = 'NO_MUTASI_KELUAR';
    public const NO_MUTATION_IN = 'NO_MUTASI_MASUK';

    public const NO_ORDER_PEMBELIAN_ASET_TETAP = 'NO_ORDER_PEMBELIAN_ASET_TETAP';
    public const NO_UANG_MUKA_PEMBELIAN_ASET_TETAP = 'NO_UANG_MUKA_PEMBELIAN_ASET_TETAP';
    public const NO_PENERIMAAN_PEMBELIAN_ASET_TETAP = 'NO_PENERIMAAN_PEMBELIAN_ASET_TETAP';
    public const NO_INVOICE_PEMBELIAN_ASET_TETAP = 'NO_INVOICE_PEMBELIAN_ASET_TETAP';
    public const NO_PELUNASAN_PEMBELIAN_ASET_TETAP = 'NO_PELUNASAN_PEMBELIAN_ASET_TETAP';
    public const NO_DEPRESIASI_ASET_TETAP = 'NO_DEPRESIASI_ASET_TETAP';
    public const NO_SALES_INVOICE_ASET_TETAP = 'NO_PENJUALAN_ASET_TETAP';
    public const NO_SALES_PAYMENT_ASET_TETAP = 'NO_PELUNASAN_PENJUALAN_ASET_TETAP';
}
